  ### GET All users:
GET http://localhost:8080/api/v1/users

### Add a user:
POST http://localhost:9090/api/v1/users/resiter
Content-Type: application/json

{
  "name": {
    "first": "root",
    "last": "admin"
  },
 
  "phone": "050-8123091",
  "email": "alsd@gmail.com",
  "password": "ababABAB1234!" 
}


### Login:
POST http://localhost:9090/api/v1/users/login
Content-Type: application/json

{
  "email": "regular@mail.com",
  "password": "ababABAB1234!"
}

### get Wayne by id with JWT of Willis:
GET http://localhost:8080/api/v1/users/65784e0a927be706a0d28789
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldpbGxpc0BiYXRjYXZlLmNvbSIsImlhdCI6MTcwMjgwMDcwNn0.pZDlu6NmQdZhGH1ZDKK5dJAaRY-5S5Dvh3HY6Z4G1Eg


### GET Willis by id with jwt of Willis
GET http://localhost:8080/api/v1/users/65784e4a927be706a0d2878f
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldpbGxpc0BiYXRjYXZlLmNvbSIsImlhdCI6MTcwMjgwMDcwNn0.pZDlu6NmQdZhGH1ZDKK5dJAaRY-5S5Dvh3HY6Z4G1Eg


### GET Wayne with JWT of admin:
GET http://localhost:8080/api/v1/users/65784e0a927be706a0d28789
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcwMjgwMDg3Nn0.1UBbvM-gXol-pr21_FTWYARyVBYzwfMD9QLs8V8tA4o


### PUT Bruce Wayne with JWT of Wayne:
PUT http://localhost:8080/api/v1/users/65784e0a927be706a0d28789
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldheW5lQGJhdGNhdmUuY29tIiwiaWF0IjoxNzAyODA3MzE4fQ.t2i7Kuyd4_HbuLqDUT0AWXy62v0zfXd8m5HIGP2nN2E
Content-Type: application/json

{
  "name": {
    "first": "Bruce!!!",
    "last": "Wayne!!!"
  },
 
  "phone": "050-8123091",
  "email": "Wayne@batcave.com",
  "password": "123456aA!" 
}